---
- hosts: all
  become: true
  become_user : root
  remote_user: root
  gather_facts: false
  tasks:
    - name: install apache web server
      yum:
        pkg: httpd
        state: present
        update_cache: true
