---
- hosts: all
  become: true
  become_user : root
  remote_user: root
  gather_facts: false
  tasks:
    - name: install HAproxy load balancer server
      yum:
        pkg: haproxy
        state: present
        update_cache: yes
    
    - name: pushes configuration
      vars:
        backend: "{{ groups['web-server'] }}"
      template: 
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: 0640
        owner: root
        group: root
      notify: 
        - restart haproxy


    - name: Sets default starting flag to 1
      lineinfile:
        dest: /etc/default/haproxy
        regexp: "^ENABLED"
        line: "ENABLED=1"
      notify:
        - restart haproxy

  handlers:
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted
